// <auto-generated/>
#pragma warning disable CS0618
using LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTaskAbort;
using LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTaskNext;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LGDXRobotCloud.UI.Client.Automation.AutoTasksApi
{
    /// <summary>
    /// Builds and executes requests for operations under \Automation\AutoTasksApi
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutoTasksApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AutoTaskAbort property</summary>
        public global::LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTaskAbort.AutoTaskAbortRequestBuilder AutoTaskAbort
        {
            get => new global::LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTaskAbort.AutoTaskAbortRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AutoTaskNext property</summary>
        public global::LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTaskNext.AutoTaskNextRequestBuilder AutoTaskNext
        {
            get => new global::LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTaskNext.AutoTaskNextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTasksApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutoTasksApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/AutoTasksApi", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Automation.AutoTasksApi.AutoTasksApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutoTasksApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Automation/AutoTasksApi", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
