// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ActivityLogListDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action property</summary>
        public int? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The entityId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityId { get; set; }
#nullable restore
#else
        public string EntityId { get; set; }
#endif
        /// <summary>The entityName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityName { get; set; }
#nullable restore
#else
        public string EntityName { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user? User { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto"/> and sets the default values.
        /// </summary>
        public ActivityLogListDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetIntValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "entityId", n => { EntityId = n.GetStringValue(); } },
                { "entityName", n => { EntityName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "user", n => { User = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user>(global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("action", Action);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("entityId", EntityId);
            writer.WriteStringValue("entityName", EntityName);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto_userMember1"/>, <see cref="global::LGDXRobotCloud.UI.Client.Models.LgdxUserSearchDto"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActivityLogListDto_user : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto_userMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto_userMember1? ActivityLogListDtoUserMember1 { get; set; }
#nullable restore
#else
            public global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto_userMember1 ActivityLogListDtoUserMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::LGDXRobotCloud.UI.Client.Models.LgdxUserSearchDto"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::LGDXRobotCloud.UI.Client.Models.LgdxUserSearchDto? LgdxUserSearchDto { get; set; }
#nullable restore
#else
            public global::LGDXRobotCloud.UI.Client.Models.LgdxUserSearchDto LgdxUserSearchDto { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto.ActivityLogListDto_user();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityLogListDtoUserMember1 = new global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto_userMember1();
                }
                else if("LgdxUserSearchDto".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.LgdxUserSearchDto = new global::LGDXRobotCloud.UI.Client.Models.LgdxUserSearchDto();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActivityLogListDtoUserMember1 != null)
                {
                    return ActivityLogListDtoUserMember1.GetFieldDeserializers();
                }
                else if(LgdxUserSearchDto != null)
                {
                    return LgdxUserSearchDto.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ActivityLogListDtoUserMember1 != null)
                {
                    writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.ActivityLogListDto_userMember1>(null, ActivityLogListDtoUserMember1);
                }
                else if(LgdxUserSearchDto != null)
                {
                    writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.LgdxUserSearchDto>(null, LgdxUserSearchDto);
                }
            }
        }
    }
}
#pragma warning restore CS0618
