// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MapEditorUpdateDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The waypoints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LGDXRobotCloud.UI.Client.Models.WaypointUpsertDto>? Waypoints { get; set; }
#nullable restore
#else
        public List<global::LGDXRobotCloud.UI.Client.Models.WaypointUpsertDto> Waypoints { get; set; }
#endif
        /// <summary>The waypointTraffics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto>? WaypointTraffics { get; set; }
#nullable restore
#else
        public List<global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto> WaypointTraffics { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.MapEditorUpdateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.MapEditorUpdateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.MapEditorUpdateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "waypointTraffics", n => { WaypointTraffics = n.GetCollectionOfObjectValues<global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto>(global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "waypoints", n => { Waypoints = n.GetCollectionOfObjectValues<global::LGDXRobotCloud.UI.Client.Models.WaypointUpsertDto>(global::LGDXRobotCloud.UI.Client.Models.WaypointUpsertDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::LGDXRobotCloud.UI.Client.Models.WaypointUpsertDto>("waypoints", Waypoints);
            writer.WriteCollectionOfObjectValues<global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto>("waypointTraffics", WaypointTraffics);
        }
    }
}
#pragma warning restore CS0618
