// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TriggerDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The apiKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey? ApiKey { get; set; }
#nullable restore
#else
        public global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey ApiKey { get; set; }
#endif
        /// <summary>The apiKeyFieldName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKeyFieldName { get; set; }
#nullable restore
#else
        public string ApiKeyFieldName { get; set; }
#endif
        /// <summary>The apiKeyInsertLocationId property</summary>
        public int? ApiKeyInsertLocationId { get; set; }
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The httpMethodId property</summary>
        public int? HttpMethodId { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Models.TriggerDto"/> and sets the default values.
        /// </summary>
        public TriggerDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.TriggerDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.TriggerDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.TriggerDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiKey", n => { ApiKey = n.GetObjectValue<global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey>(global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey.CreateFromDiscriminatorValue); } },
                { "apiKeyFieldName", n => { ApiKeyFieldName = n.GetStringValue(); } },
                { "apiKeyInsertLocationId", n => { ApiKeyInsertLocationId = n.GetIntValue(); } },
                { "body", n => { Body = n.GetStringValue(); } },
                { "httpMethodId", n => { HttpMethodId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey>("apiKey", ApiKey);
            writer.WriteStringValue("apiKeyFieldName", ApiKeyFieldName);
            writer.WriteIntValue("apiKeyInsertLocationId", ApiKeyInsertLocationId);
            writer.WriteStringValue("body", Body);
            writer.WriteIntValue("httpMethodId", HttpMethodId);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::LGDXRobotCloud.UI.Client.Models.ApiKeySearchDto"/>, <see cref="global::LGDXRobotCloud.UI.Client.Models.TriggerDto_apiKeyMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TriggerDto_apiKey : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::LGDXRobotCloud.UI.Client.Models.ApiKeySearchDto"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::LGDXRobotCloud.UI.Client.Models.ApiKeySearchDto? ApiKeySearchDto { get; set; }
#nullable restore
#else
            public global::LGDXRobotCloud.UI.Client.Models.ApiKeySearchDto ApiKeySearchDto { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::LGDXRobotCloud.UI.Client.Models.TriggerDto_apiKeyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::LGDXRobotCloud.UI.Client.Models.TriggerDto_apiKeyMember1? TriggerDtoApiKeyMember1 { get; set; }
#nullable restore
#else
            public global::LGDXRobotCloud.UI.Client.Models.TriggerDto_apiKeyMember1 TriggerDtoApiKeyMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::LGDXRobotCloud.UI.Client.Models.TriggerDto.TriggerDto_apiKey();
                if("ApiKeySearchDto".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ApiKeySearchDto = new global::LGDXRobotCloud.UI.Client.Models.ApiKeySearchDto();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.TriggerDtoApiKeyMember1 = new global::LGDXRobotCloud.UI.Client.Models.TriggerDto_apiKeyMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ApiKeySearchDto != null)
                {
                    return ApiKeySearchDto.GetFieldDeserializers();
                }
                else if(TriggerDtoApiKeyMember1 != null)
                {
                    return TriggerDtoApiKeyMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ApiKeySearchDto != null)
                {
                    writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.ApiKeySearchDto>(null, ApiKeySearchDto);
                }
                else if(TriggerDtoApiKeyMember1 != null)
                {
                    writer.WriteObjectValue<global::LGDXRobotCloud.UI.Client.Models.TriggerDto_apiKeyMember1>(null, TriggerDtoApiKeyMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
