// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WaypointCreateDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The className property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassName { get; set; }
#nullable restore
#else
        public string ClassName { get; set; }
#endif
        /// <summary>The featureId property</summary>
        public int? FeatureId { get; set; }
        /// <summary>The isDocking property</summary>
        public bool? IsDocking { get; set; }
        /// <summary>The isIntermediate property</summary>
        public bool? IsIntermediate { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The realmId property</summary>
        public int? RealmId { get; set; }
        /// <summary>The rotation property</summary>
        public double? Rotation { get; set; }
        /// <summary>The x property</summary>
        public double? X { get; set; }
        /// <summary>The y property</summary>
        public double? Y { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.WaypointCreateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.WaypointCreateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.WaypointCreateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "className", n => { ClassName = n.GetStringValue(); } },
                { "featureId", n => { FeatureId = n.GetIntValue(); } },
                { "isDocking", n => { IsDocking = n.GetBoolValue(); } },
                { "isIntermediate", n => { IsIntermediate = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "realmId", n => { RealmId = n.GetIntValue(); } },
                { "rotation", n => { Rotation = n.GetDoubleValue(); } },
                { "x", n => { X = n.GetDoubleValue(); } },
                { "y", n => { Y = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("className", ClassName);
            writer.WriteIntValue("featureId", FeatureId);
            writer.WriteBoolValue("isDocking", IsDocking);
            writer.WriteBoolValue("isIntermediate", IsIntermediate);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("realmId", RealmId);
            writer.WriteDoubleValue("rotation", Rotation);
            writer.WriteDoubleValue("x", X);
            writer.WriteDoubleValue("y", Y);
        }
    }
}
#pragma warning restore CS0618
