// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LGDXRobotCloud.UI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WaypointTrafficUpdateDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The absoluteSpeedLimit property</summary>
        public double? AbsoluteSpeedLimit { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alternativeWaypointFromId property</summary>
        public Guid? AlternativeWaypointFromId { get; set; }
        /// <summary>The alternativeWaypointToId property</summary>
        public Guid? AlternativeWaypointToId { get; set; }
        /// <summary>The cost property</summary>
        public double? Cost { get; set; }
        /// <summary>The featureId property</summary>
        public int? FeatureId { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The overridable property</summary>
        public bool? Overridable { get; set; }
        /// <summary>The speedLimit property</summary>
        public double? SpeedLimit { get; set; }
        /// <summary>The waypointFromId property</summary>
        public int? WaypointFromId { get; set; }
        /// <summary>The waypointToId property</summary>
        public int? WaypointToId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto"/> and sets the default values.
        /// </summary>
        public WaypointTrafficUpdateDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::LGDXRobotCloud.UI.Client.Models.WaypointTrafficUpdateDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absoluteSpeedLimit", n => { AbsoluteSpeedLimit = n.GetDoubleValue(); } },
                { "alternativeWaypointFromId", n => { AlternativeWaypointFromId = n.GetGuidValue(); } },
                { "alternativeWaypointToId", n => { AlternativeWaypointToId = n.GetGuidValue(); } },
                { "cost", n => { Cost = n.GetDoubleValue(); } },
                { "featureId", n => { FeatureId = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "overridable", n => { Overridable = n.GetBoolValue(); } },
                { "speedLimit", n => { SpeedLimit = n.GetDoubleValue(); } },
                { "waypointFromId", n => { WaypointFromId = n.GetIntValue(); } },
                { "waypointToId", n => { WaypointToId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("absoluteSpeedLimit", AbsoluteSpeedLimit);
            writer.WriteGuidValue("alternativeWaypointFromId", AlternativeWaypointFromId);
            writer.WriteGuidValue("alternativeWaypointToId", AlternativeWaypointToId);
            writer.WriteDoubleValue("cost", Cost);
            writer.WriteIntValue("featureId", FeatureId);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("overridable", Overridable);
            writer.WriteDoubleValue("speedLimit", SpeedLimit);
            writer.WriteIntValue("waypointFromId", WaypointFromId);
            writer.WriteIntValue("waypointToId", WaypointToId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
