[ req ]
distinguished_name       = req_distinguished_name
extensions               = v3_ca
req_extensions           = v3_ca
prompt                   = no 

[ v3_ca ]
basicConstraints         = CA:TRUE

[ req_distinguished_name ]
countryName              = GB
stateOrProvinceName      = Ayrshire
localityName             = Alloway
organizationName         = LGDXRobot Test
organizationalUnitName   = Quality Assurance Department
commonName               = LGDXRobot Cloud Root CA For Testing
emailAddress             = murray@example.com
